set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR "x86_64")

#set(triple i686-pc-none-elf)
set(CMAKE_CXX_COMPILER gcc)
set(CMAKE_C_COMPILER gcc)
set(CMAKE_ASM_COMPILER gcc)
#set(CMAKE_CXX_COMPILER_TARGET ${triple})
#set(CMAKE_C_COMPILER_TARGET ${triple})
#set(CMAKE_ASM_COMPILER_TARGET ${triple})

set(CMAKE_CXX_FLAGS "-Wall -Wextra -Werror")
set(CMAKE_C_FLAGS "-Wall -Wextra -Werror")
set(CMAKE_LINK_FLAGS)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)